---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "App dashboard"
subtitle: "Tiger X Daphne"
logo: "assets/logo.png"

header: true # Set to false to hide the header
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

# Optional theming
theme: default # 'default' or one of the theme available in 'src/assets/themes'.

# Here is the exaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message, TODO expose API for this
# message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.

# Optional navbar
links:
  - name: "Tiger"
    icon: "fas fa-male"
    url: "https://tigeroakes.com"
  - name: "Daphne"
    icon: "fas fa-female"
    url: "https://daphneliu.com"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Smart home"
    icon: "fa fa-laptop-house"
    items:
      - name: "WebThings"
        logo: "https://raw.githubusercontent.com/mozilla-iot/gateway/master/static/images/icon-2x.png"
        subtitle: "Simple smart home UI"
        url: "https://tigerxdaphne.mozilla-iot.org/"
      - name: "Home Assistant"
        logo: "https://www.home-assistant.io/images/home-assistant-logo.svg"
        subtitle: "Advanced configuration"
        url: "https://home.tigeroakes.com"
  - name: "Media"
    icon: "fas fa-compact-disc"
    items:
      - name: "Plex"
        logo: "https://www.plex.tv/wp-content/themes/plex/assets/img/favicons/apple-touch-icon-152x152.png"
        subtitle: "TV, Movies, Audiobooks, and more"
        url: "https://app.plex.tv/"
      - name: "Calibre Web"
        logo: "https://books.home.tigeroakes.com/static/favicon.ico"
        subtitle: "eBooks and Kobo server"
        url: "https://books.home.tigeroakes.com"
      - name: "Komga"
        logo: "https://komga.org/assets/media/logo.svg"
        subtitle: "Comics/mangas server"
        url: "https://comics.home.tigeroakes.com"
  - name: "Configuration"
    icon: "fas fa-server"
    items:
      - name: "Router"
        logo: "fas fa-ethernet"
        subtitle: "WAN and LAN settings"
        url: "http://router.asus.com"
      - name: "Filestash"
        logo: "https://downloads.filestash.app/brand/logo_white.svg"
        subtitle: "SFTP connection"
        url: "http://<ipaddr>:8334"
