version: "3.7"
services:

  # Proxy localhost websites on different ports to one single site
  caddy:
    image: caddy
    restart: always
    container_name: caddy
    network_mode: host
    volumes:
      - "/home/tiger/.caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "~/.caddy/data:/data"
      - "~/.caddy/config:/config"

  # Dashboard
  homer:
    image: b4bz/homer
    restart: always
    container_name: homer
    ports:
      - "8008:8080"
    volumes:
      - "/home/tiger/.homer:/www/assets"

  # Share media
  plex:
    image: plexinc/pms-docker
    restart: always
    container_name: plex
    network_mode: host
    environment:
      TZ: "America/Vancouver"
      # PLEX_CLAIM: "<claimToken>"
    volumes:
      - "~/.plex/config:/config"
      - "~/.plex/transcode:/transcode"
      - "/media/passport/Media:/data"

  # Plex voice interface
  flextv:
    image: digitalhigh/flextv
    container_name: flextv
    restart: always
    environment:
      TZ: "America/Vancouver"
    ports:
      - "32200:80"
    volumes:
      - "~/.plex/flextv:/config"

  # WebThings
  webthings:
    image: mozillaiot/gateway
    restart: always
    container_name: webthings-gateway
    network_mode: host
    environment:
      TZ: "America/Vancouver"
    volumes:
      - "~/.mozilla-iot:/home/node/.mozilla-iot"
    logging:
      options:
        max-size: "1m"
        max-file: "10"

  # Book storage
  calibre:
    image: linuxserver/calibre
    restart: always
    container_name: calibre
    environment:
      TZ: "America/Vancouver"
    volumes:
      - "~/.calibre/config:/config"
      - "/media/passport/Books:/Calibre_Library"
    ports:
      - "27880:8080"
      - "27881:8081"

  # Book access
  calibreweb:
    image: linuxserver/calibre-web
    restart: always
    container_name: calibre-web
    environment:
      TZ: "America/Vancouver"
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
    volumes:
      - "~/.calibre/webconfig:/config"
      - "/media/passport/Books:/books"
    ports:
      - "27883:8083"

  # Comics
  komga:
    image: gotson/komga
    restart: always
    container_name: komga
    environment:
      TZ: "America/Vancouver"
      SPRING_PROFILES_ACTIVE: "claim"
    volumes:
      - "~/.komga/config:/config"
      - "/media/passport/Comics:/books"
    ports:
      - "27885:8080"

  youtubedl:
    container_name: youtubedl
    image: tzahi12345/youtubedl-material
    restart: always
    environment:
      ALLOW_CONFIG_MUTATIONS: 'true'
    volumes:
      - ~/.youtubedl/appdata:/app/appdata
      - ~/.youtubedl/audio:/app/audio
      - ~/.youtubedl/video:/app/video
      - ~/.youtubedl/subscriptions:/app/subscriptions
      - ~/.youtubedl/users:/app/users
    ports:
      - "17442:17442"

  # FTP
  filestash:
    container_name: filestash
    image: machines/filestash
    restart: always
    ports:
      - "8334:8334"

  # IRC
  thelounge:
    container_name: thelounge
    image: thelounge/thelounge
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ~/.thelounge:/var/opt/thelounge

  # Share files with Windows
  samba:
    container_name: samba
    image: dperson/samba
    restart: always
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - "/media/passport:/mount:z"
    command: '-s "Media;/mount;yes;no" -u "tiger;dactylion" -p'

  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: always
    environment:
      - UMASK_SET=022
      - WEBUI_PORT=27501
    volumes:
      - ~/.qbittorrent/config:/config
      - /media/passport/Download:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 27501:27501

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ~/.jackett/config:/config
      - /media/passport/Download:/downloads
    ports:
      - 9117:9117
    restart: always
    network_mode: host

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ~/.sonarr/config:/config
      - /media/passport/Media/TV:/tv
      - /media/passport/Download:/downloads
    ports:
      - 8989:8989
    restart: always
    network_mode: host

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    volumes:
      - ~/.radarr/config:/config
      - /media/passport/Media/Movies:/tv
      - /media/passport/Download:/downloads
    ports:
      - 7878:7878
    network_mode: host
