version: "3.7"
services:

  # Proxy localhost websites on different ports to one single site
  caddy:
    image: caddy
    restart: always
    container_name: caddy
    network_mode: host
    volumes:
      - "/home/tiger/.caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "~/.caddy/data:/data"
      - "~/.caddy/config:/config"

  # Dashboard
  homer:
    image: b4bz/homer
    restart: always
    container_name: homer
    ports:
      - "8008:8080"
    volumes:
      - "/home/tiger/.homer:/www/assets"

  # Share media
  plex:
    image: plexinc/pms-docker
    restart: always
    container_name: plex
    network_mode: host
    environment:
      TZ: "America/Vancouver"
      # PLEX_CLAIM: "<claimToken>"
    volumes:
      - "~/.plex/config:/config"
      - "~/.plex/transcode:/transcode"
      - "/media/passport/Media:/data"

  # Plex voice interface
  flextv:
    image: digitalhigh/flextv
    container_name: flextv
    restart: always
    environment:
      TZ: "America/Vancouver"
    ports:
      - "32200:80"
    volumes:
      - "~/.plex/flextv:/config"

  # WebThings
  webthings:
    image: mozillaiot/gateway
    restart: always
    container_name: webthings-gateway
    network_mode: host
    environment:
      TZ: "America/Vancouver"
    volumes:
      - "~/.mozilla-iot:/home/node/.mozilla-iot"
    logging:
      options:
        max-size: "1m"
        max-file: "10"

  # Book storage
  calibre:
    image: linuxserver/calibre
    restart: always
    container_name: calibre
    environment:
      TZ: "America/Vancouver"
    volumes:
      - "~/.calibre/config:/config"
      - "/media/passport/Books:/Calibre_Library"
    ports:
      - "27880:8080"
      - "27881:8081"

  # Book access
  calibreweb:
    image: linuxserver/calibre-web
    restart: always
    container_name: calibre-web
    environment:
      TZ: "America/Vancouver"
      DOCKER_MODS: "linuxserver/calibre-web:calibre"
    volumes:
      - "~/.calibre/webconfig:/config"
      - "/media/passport/Books:/books"
    ports:
      - "27883:8083"

  # Comics
  komga:
    image: gotson/komga
    restart: always
    container_name: komga
    environment:
      TZ: "America/Vancouver"
      SPRING_PROFILES_ACTIVE: "claim"
    volumes:
      - "~/.komga/config:/config"
      - "/media/passport/Comics:/books"
    ports:
      - "27885:8080"

  # FTP
  filestash:
    container_name: filestash
    image: machines/filestash
    restart: always
    ports:
      - "8334:8334"
